extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:jsx-a11y/recommended
env:
  browser: true
  node: true
  es6: true
settings:
  react:
    version: detect

overrides:
  - files: ["*.ts", "*.tsx"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      sourceType: module
      ecmaFeatures:
        jsx: true
    extends:
      - plugin:react/recommended
      - plugin:@typescript-eslint/recommended
    plugins:
      - "@typescript-eslint"
      - react
      - import
      - react-hooks
      - "@emotion"
    rules:
      "eqeqeq":
        - error
        - always
        - null: ignore
      "import/no-default-export": error
      "no-console":
        - error
        - allow:
            - info
            - warn
            - error
            - group
            - groupCollapsed
            - groupEnd
      "no-restricted-imports":
        - error
        - paths:
          - name: "@emotion/css"
            message: 'Use `import { css } from "@emotion/react"` instead.'
      "@typescript-eslint/no-explicit-any": "off"
      "react/prop-types": "off"
      "no-unused-vars": "off"
      "@typescript-eslint/no-unused-vars":
        - warn
        - argsIgnorePattern: "^_"
      "@typescript-eslint/naming-convention":
        - error
        # 変数名は camelCase, PascalCase, UPPER_CASE
        - selector: default
          format: [camelCase, PascalCase, UPPER_CASE]
        # 引数は基本的に camelCase、ライブラリの仕様で PascalCase になる場合もあるので PascalCase も許可。
        # _ で始まる引数は未使用引数として利用するので leadingUnderscore を許可。
        - selector: parameter
          format: [camelCase, PascalCase]
          leadingUnderscore: allow
        # 型名は PascalCase
        - selector: typeLike
          format: [PascalCase]
        # オブジェクトのキーは API リクエストの body などで _ や - が利用されることがあるので全て許可
        - selector: [classProperty, objectLiteralProperty, typeProperty]
          format: null
      "react-hooks/rules-of-hooks": "error"
      "react-hooks/exhaustive-deps": "error"
      "react/jsx-no-target-blank":
        - error
        - allowReferrer: true
      "react/react-in-jsx-scope": "off"
      "react/button-has-type": "error"
