#!/bin/sh -eux

NODE_VERSION=14

if !(type "node" > /dev/null 2>&1); then
  echo "❌ Please install node v$NODE_VERSION."
  exit 1;
fi
if [[ ! `node -v` =~ ^v$NODE_VERSION.+$ ]]; then
  echo "❌ Please use node v$NODE_VERSION. Your current node version is `node -v`"
  exit 1;
fi
if !(type "yarn" > /dev/null 2>&1); then
  echo "❌ Please install yarn."
  exit 1;
fi

PROJECT_ROOT=$(cd $(dirname $0)/.. && pwd)
cd $PROJECT_ROOT

# dev
cd dev
yarn install
cd -

# api
cd api
yarn install
if [[ `uname -m` == 'arm64' ]] && [[ `uname -s` == 'Darwin' ]]; then
  # Workaround for M1 Mac
  # @see https://github.com/Azure/azure-functions-nodejs-worker/issues/386#issuecomment-778550469
  ln -sf "$PROJECT_ROOT/api/node_modules/grpc/src/node/extension_binary/node-v83-darwin-arm64-unknown" "$PROJECT_ROOT/api/node_modules/azure-functions-core-tools/bin/workers/node/grpc/src/node/extension_binary"
fi
yarn build
cd -

# frontend
yarn install
yarn build

printf "✅ Setup has been succeeded."
